name: Build Microcks Desktop

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Cache Electron caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json', '**/package.json') }}

      - name: Install system deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm libarchive-tools

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Bundle JRE into app (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p jre
          cp -a "$JAVA_HOME/." jre/

      - name: Bundle JRE into app (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force jre | Out-Null
          Copy-Item -Path "$env:JAVA_HOME\*" -Destination jre -Recurse -Force

      - name: Build app
        env:
          # Avoid failing mac builds when no signing certs are configured
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: 'true'
        run: |
          npm run build:main
          npx electron-builder --publish=never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: microcks-desktop-${{ runner.os }}
          path: dist/**
          if-no-files-found: error
